$(document).ready(function() {
  $("#js").click(function(){
    $("p").removeClass("show");
    $("#jsdef").addClass("show");
    $("li").removeClass("font");
    $("#js").addClass("font");
    $(".examples").removeClass("show");
    $("#jsex").addClass("show");
  });
  $("#op").click(function(){
    $("p").removeClass("show");
    $("#opdef").addClass("show");
    $("li").removeClass("font");
    $("#op").addClass("font");
    $(".examples").removeClass("show");
    $("#opex").addClass("show");

  });
  $("#var").click(function(){
    $("p").removeClass("show");
    $("li").removeClass("font");
    $("#vardef").addClass("show");
    $("#var").addClass("font");
  });
  $("#vnc").click(function(){
    $("p").removeClass("show");
    $("li").removeClass("font");
    $("#vncdef").addClass("show");
    $("#vnc").addClass("font");
  });
  $("#func").click(function(){
    $("p").removeClass("show");
    $("li").removeClass("font");
    $("#funcdef").addClass("show");
    $("#func").addClass("font");
  });
  $("#meth").click(function(){
    $("p").removeClass("show");
    $("li").removeClass("font");
    $("#methdef").addClass("show");
    $("#meth").addClass("font");
  });
  $("#ar").click(function(){
    $("p").removeClass("show");
    $("li").removeClass("font");
    $("#ardef").addClass("show");
    $("#ar").addClass("font");
  });
  $("#prm").click(function(){
    $("p").removeClass("show");
    $("li").removeClass("font");
    $("#prmdef").addClass("show");
    $("#prm").addClass("font");
  });
  $("#ret").click(function(){
    $("p").removeClass("show");
    $("li").removeClass("font");
    $("#retdef").addClass("show");
    $("#ret").addClass("font");
  });
  $("#cm").click(function(){
    $("p").removeClass("show");
    $("li").removeClass("font");
    $("#cmdef").addClass("show");
    $("#cm").addClass("font");
  });
  $("#ss").click(function(){
    $("p").removeClass("show");
    $("li").removeClass("font");
    $("#ssdef").addClass("show");
    $("#ss").addClass("font");
  });
  $("#bs").click(function(){
    $("p").removeClass("show");
    $("li").removeClass("font");
    $("#bsdef").addClass("show");
    $("#bs").addClass("font");
  });
  $("#ud").click(function(){
    $("p").removeClass("show");
    $("li").removeClass("font");
    $("#uddef").addClass("show");
    $("#ud").addClass("font");
  });
  $("#nan").click(function(){
    $("p").removeClass("show");
    $("li").removeClass("font");
    $("#nandef").addClass("show");
    $("#nan").addClass("font");
  });
  $("#ee").click(function(){
    $("p").removeClass("show");
    $("li").removeClass("font");
    $("#eedef").addClass("show");
    $("#ee").addClass("font");
  });
  $("#alt").click(function(){
    $("p").removeClass("show");
    $("li").removeClass("font");
    $("#altdef").addClass("show");
    $("#alt").addClass("font");
  });
  $("#cs").click(function(){
    $("p").removeClass("show");
    $("li").removeClass("font");
    $("#csdef").addClass("show");
    $("#cs").addClass("font");
  });
  $("#jq").click(function(){
    $("p").removeClass("show");
    $("li").removeClass("font");
    $("#jqdef").addClass("show");
    $("#jq").addClass("font");
  });
  $("#at").click(function(){
    $("p").removeClass("show");
    $("li").removeClass("font");
    $("#atdef").addClass("show");
    $("#at").addClass("font");
  });
});
